/**
 * Virtual University of Pakistan's BS programs and the courses of each semester, as published in each program's
 * "Scheme of Study" on vu.edu.pk (AboutUs/ProgramDetails?StudyProgramID=…), read on 25 September 2026.
 * Used only to fill a program in one step; nothing here is shown to students unless an admin adds it.
 * VU revises schemes from time to time, so admins can still add, rename or remove courses by hand afterwards.
 *
 * Each course is [code, title, kind, credit hours, specialisation tracks?]. kind: R = required, E = elective,
 * D = deficiency (only for students missing a prerequisite, e.g. General Mathematics). A course VU lists in more
 * than one semester appears only in the first one.
 */

export type VuCourseKind = "R" | "E" | "D";
type Row = readonly [code: string, title: string, kind: VuCourseKind, credits: number, tracks?: string];

export type VuCourse = { code: string; title: string; kind: VuCourseKind; credits: number; tracks: string[] };
export type VuProgram = { slug: string; name: string; aliases: readonly string[]; sourceUrl: string; semesters: VuCourse[][] };

const RAW: readonly { slug: string; name: string; aliases: readonly string[]; id: number; semesters: readonly (readonly Row[])[] }[] = [
  {
    slug: "bed-early-childhood", name: "B.Ed. (Hons) Early Childhood Care and Education", aliases: ["ecce"], id: 169,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ECE101", "Introduction to Early Childhood Education", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["EDUA305", "Classroom Management for Young Learners", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["GSC101", "General Science", "R", 3],
        ["SOC201", "Social Statistics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["EDUA405", "Assessment and Evaluation in Early Years of Education", "R", 3],
        ["EDUA430", "Use of Information and Communication Technology for Early Childhood Education", "R", 3],
        ["EDUA516", "Teaching of English in Early Childhood", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["URD100", "Urdu Language", "R", 2],
      ],
      [
        ["ECTA519", "Teaching Practice - I", "R", 3],
        ["EDUA403", "Teaching of Arts, Crafts & Calligraphy", "R", 3],
        ["EDUA501", "Role of School, Community & Teacher in Early Years of Education", "R", 3],
        ["EDUA510", "Teaching of Mathematics in Early Childhood", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["GSCA201", "Teaching of General Science in Early Years of Education", "R", 3],
      ],
      [
        ["ECE201", "Language Development of the Child", "R", 3],
        ["ECE204", "Independence, Self-Management and Ethics in Early Years", "R", 3],
        ["ECE301", "Psycho Social Development of the Child", "R", 3],
        ["EDU306", "Teaching of Social Studies and Islamiat in Early Years of Education", "R", 3],
        ["PSY406", "Educational Psychology", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MGT503", "Principles of Management", "E", 3],
        ["MGTE630", "Knowledge Management", "E", 3],
        ["PSC201", "International Relations", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC301", "Introduction to Social Work", "E", 3],
        ["SOC602", "Sociology of Education", "E", 3],
        ["SOC604", "Community Development", "E", 3],
      ],
      [
        ["ECE203", "Children Literature and Educational Games", "R", 3],
        ["ECE302", "Education for Sustainable Development in Early Childhood Education", "R", 3],
        ["EDU433", "Professionalism in Teaching", "R", 3],
        ["EDUA411", "Teaching of Urdu in Early Childhood", "R", 3],
      ],
      [
        ["ECE202", "Physical Development of the Child", "R", 3],
        ["ECE402", "Trends and Issues in Early Childhood Education", "R", 3],
        ["EDU407", "Research Methods in Education", "R", 3],
        ["EDUA402", "Curriculum Development for Early Childhood Education", "R", 3],
        ["EDUA601", "Philosophical Foundations of Early Childhood Education", "R", 3],
      ],
      [
        ["ECTB519", "Teaching Practice - II", "R", 3],
        ["EDUA406", "Reflective Practices and Critical Thinking in Early Years", "R", 3],
        ["EDUA602", "Leadership and Management of Early Childhood Education Programs", "R", 3],
        ["EDUA630", "Research Project", "R", 3],
      ],
    ],
  },
  {
    slug: "bed-elementary", name: "B.Ed. (Hons) Elementary", aliases: ["bed"], id: 59,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["EDU101", "Foundations of Education", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["EDU305", "Classroom Management", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["GSC101", "General Science", "R", 3],
        ["SOC201", "Social Statistics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["EDU405", "Classroom Assessment", "R", 3],
        ["EDU430", "ICT in Education", "R", 3],
        ["EDU516", "Teaching of English", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["URD100", "Urdu Language", "R", 2],
      ],
      [
        ["EDU403", "Art, Crafts and Calligraphy", "R", 3],
        ["EDU501", "School, Community and Teacher", "R", 3],
        ["EDU510", "Teaching of Mathematics", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["GSC201", "Teaching of General Science", "R", 3],
        ["TPTA519", "Teaching Practice - I", "R", 3],
      ],
      [
        ["EDU303", "Child Development", "R", 3],
        ["EDU410", "Teaching of Literacy Skills", "R", 3],
        ["EDU411", "Teaching of Urdu", "R", 3],
        ["EDU431", "Test Development & Evaluation", "R", 3],
        ["PSY406", "Educational Psychology", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MGT503", "Principles of Management", "E", 3],
        ["MGTE630", "Knowledge Management", "E", 3],
        ["PSC201", "International Relations", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC301", "Introduction to Social Work", "E", 3],
        ["SOC602", "Sociology of Education", "E", 3],
        ["SOC604", "Community Development", "E", 3],
      ],
      [
        ["EDU304", "Introduction to Guidance and Counseling", "R", 3],
        ["EDU401", "Contemporary Issues and Trends in Education", "R", 3],
        ["EDU512", "Teaching of Islamic Studies", "R", 3],
        ["EDU601", "Philosophy of Education", "R", 3],
      ],
      [
        ["EDU402", "Curriculum Development", "R", 3],
        ["EDU406", "Critical Thinking and reflective Practice", "R", 3],
        ["EDU407", "Research Methods in Education", "R", 3],
        ["EDU433", "Professionalism in Teaching", "R", 3],
        ["EDU515", "Teaching of Geography", "R", 3],
      ],
      [
        ["EDU602", "Educational Leadership and Management", "R", 3],
        ["EDU604", "Comparative Education", "R", 3],
        ["EDUA630", "Research Project", "R", 3],
        ["TPTB519", "Teaching Practice - II", "R", 3],
      ],
    ],
  },
  {
    slug: "bbit", name: "BBIT (Business & Information Technology)", aliases: ["bbit"], id: 55,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["MGT503", "Principles of Management", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["CS201", "Introduction to Programming", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT301", "Principles of Marketing", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["PHY101", "Physics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["CS201P", "Introduction to Programming (Practical)", "R", 1],
      ],
      [
        ["CS302", "Digital Logic Design", "R", 3],
        ["CS304", "Object Oriented Programming", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["ECO302", "Principles of Microeconomics", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["ECO402", "Microeconomics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["CS302P", "Digital Logic Design (Practical)", "R", 1],
        ["CS304P", "Object Oriented Programming (Practical)", "R", 1],
      ],
      [
        ["CS403", "Database Management Systems", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT101", "Financial Accounting", "R", 3],
        ["MGT501", "Human Resource Management", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["CS403P", "Database Management Systems (Practical)", "R", 1],
      ],
      [
        ["ACC501", "Business Finance", "R", 3],
        ["CS301", "Data Structures", "R", 3],
        ["CS504", "Software Engineering - I", "R", 3],
        ["CS601", "Data Communication", "R", 3],
        ["EDU401", "Contemporary Issues and Trends in Education", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["CS301P", "Data Structures (Practical)", "R", 1],
      ],
      [
        ["CS605", "Software EngineeringII", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["MGTI699", "Internship / Field Experience", "R", 3],
        ["ECO404", "Managerial Economics", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MKT501", "Marketing Management", "E", 3],
        ["MKT530", "Consumer Behaviour", "E", 3],
        ["MKT621", "Advertising & Promotion", "E", 3],
        ["SOC617", "Social Entrepreneurship", "E", 3],
      ],
      [
        ["CS610", "Computer Networks", "R", 3],
        ["IT430", "E-Commerce", "R", 3],
        ["MGT699", "Capstone Project", "R", 3],
        ["CS310", "Open Source Web Application Development (PHP, PERL, CGI, Mysql)", "E", 3],
        ["CS615", "Software Project Management", "E", 3],
        ["MCM601", "Media Management", "E", 3],
        ["PSY405", "Personality Psychology", "E", 3],
        ["CS610P", "Computer Networks (Practical)", "R", 1],
      ],
      [
        ["CS614", "Data Warehousing", "R", 3],
        ["MGT611", "Business & Labor Law", "R", 3],
        ["CS407", "Routing and Switching", "E", 3],
        ["CS408", "Human Computer Interaction", "E", 3],
        ["EDU406", "Critical Thinking and reflective Practice", "E", 3],
        ["MGMT614", "Supply Chain Management", "E", 3],
        ["MGT402", "Cost & Management Accounting", "E", 3],
        ["SOC404", "Pakistani Society and Culture", "E", 3],
      ],
    ],
  },
  {
    slug: "accounting-finance", name: "BS Accounting & Finance", aliases: ["bsaf","accounting"], id: 1,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["MGT503", "Principles of Management", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT101", "Financial Accounting", "R", 3],
        ["MGT301", "Principles of Marketing", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["ACC501", "Business Finance", "R", 3],
        ["MGT401", "Financial Accounting II", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["ECO302", "Principles of Microeconomics", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["ECO402", "Microeconomics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ACC101", "QuickBooks", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT402", "Cost & Management Accounting", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["GSC101", "General Science", "E", 3],
        ["PHY101", "Physics", "E", 3],
      ],
      [
        ["ACC311", "Fundamentals of Auditing", "R", 3],
        ["ECO404", "Managerial Economics", "R", 3],
        ["FIN624", "Islamic Modes of Finance", "R", 3],
        ["MGT201", "Financial Management", "R", 3],
        ["STA630", "Research Methods", "R", 3],
      ],
      [
        ["FIN611", "Advanced Financial Accounting", "R", 3],
        ["MGT501", "Human Resource Management", "R", 3],
        ["MGT610", "Business Ethics", "R", 3],
        ["MGTI699", "Internship / Field Experience", "R", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MCM601", "Media Management", "E", 3],
      ],
      [
        ["FIN621", "Financial Statement Analysis", "R", 3],
        ["MGT611", "Business & Labor Law", "R", 3],
        ["MGT699", "Capstone Project", "R", 3],
        ["EDU401", "Contemporary Issues and Trends in Education", "E", 3],
        ["EDU406", "Critical Thinking and reflective Practice", "E", 3],
        ["MGT404", "Managerial Accounting", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT605", "Advanced Cost and Management Accounting", "E", 3],
        ["MKT530", "Consumer Behaviour", "E", 3],
      ],
      [
        ["FIN622", "Corporate Finance", "R", 3],
        ["MGT612", "Corporate Law", "R", 3],
        ["FIN623", "Taxation Management", "E", 3],
        ["FIN630", "Investment Analysis & Portfolio Management", "E", 3],
        ["MGMT622", "Management Skills", "E", 3],
        ["MGT601", "SME Management", "E", 3],
        ["PSY405", "Personality Psychology", "E", 3],
        ["SOC617", "Social Entrepreneurship", "E", 3],
      ],
    ],
  },
  {
    slug: "bioinformatics", name: "BS Bioinformatics", aliases: ["bioinformatics"], id: 108,
    semesters: [
      [
        ["BIO5105", "Cell Biology", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["BIO102", "Basic II-Chemistry", "E", 3],
        ["CS101", "Introduction to Computing", "E", 3],
        ["MTH100", "General Mathematics", "E", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["MB501P", "Cell Biology (Practical)", "R", 1],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["BIO504T", "Biochemistry I (Theory)", "R", 3],
        ["BIO505T", "Essentials of Genetics (Theory)", "R", 3],
        ["CS201", "Introduction to Programming", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["BIO504P", "Biochemistry I (Practical)", "R", 1],
        ["BIO505P", "Essentials of Genetics (Practical)", "R", 1],
        ["CS201P", "Introduction to Programming (Practical)", "R", 1],
      ],
      [
        ["BIF401", "Bioinformatics I", "R", 3],
        ["CS301", "Data Structures", "R", 3],
        ["ENG301", "Business Communication", "R", 3],
        ["MB502T", "Molecular Biology (Theory)", "R", 3],
        ["MTH303", "Mathematical Methods", "R", 3],
        ["BIF401P", "Bioinformatics I (Practical)", "R", 1],
        ["CS301P", "Data Structures (Practical)", "R", 1],
        ["MB502P", "Molecular Biology (Practical)", "R", 1],
      ],
      [
        ["BIF501", "Bioinformatics II", "R", 3],
        ["BIO506T", "Biochemistry II (Theory)", "R", 3],
        ["CS304", "Object Oriented Programming", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["BIF498", "Research Project", "E", 3],
        ["BT406", "Research Methodology & Skill Enhancement", "E", 3],
        ["BIF501P", "Bioinformatics II (Practical)", "R", 1],
        ["BIO506P", "Biochemistry II (Practical)", "R", 1],
        ["CS304P", "Object Oriented Programming (Practical)", "R", 1],
      ],
      [
        ["BIO401", "Biostatistics", "R", 3],
        ["CS403", "Database Management Systems", "R", 3],
        ["CS408", "Human Computer Interaction", "R", 3],
        ["CS502", "Fundamentals of Algorithms", "R", 3],
        ["MB504P", "Methods in Molecular Biology (Practical)", "R", 2],
        ["CS403P", "Database Management Systems (Practical)", "R", 1],
        ["MB504T", "Methods in Molecular Biology (Theory)", "R", 1],
      ],
      [
        ["BIF601", "Bioinformatics Computing I", "R", 3],
        ["BIO502", "Genomics", "R", 3],
        ["BIO5101", "Introduction to Biotechnology", "R", 3],
        ["BT505", "Biosensors", "R", 3],
        ["CS504", "Software Engineering - I", "R", 3],
        ["BIF601P", "Bioinformatics Computing I (Practical)", "R", 1],
        ["BT511P", "Introduction to Biotechnology (Practical)", "R", 1],
      ],
      [
        ["BIF499A", "Final Year Project", "R", 3],
        ["BIF602", "Bioinformatics Computing II", "R", 3],
        ["BIO601", "Proteomics", "R", 3],
        ["CS602", "Computer Graphics", "R", 3],
        ["CS620", "Modelling and Simulation", "R", 3],
        ["BT512T", "Microbial Biotechnology (Theory)", "R", 2],
        ["BT512P", "Microbial Biotechnology (Practical)", "R", 1],
      ],
      [
        ["BIF499B", "Final Year Project", "R", 3],
        ["BIF604", "Special Topics in Bioinformatics", "R", 3],
        ["CS607", "Artificial Intelligence", "R", 3],
        ["CS614", "Data Warehousing", "R", 3],
        ["CS607P", "Artificial Intelligence (Practical)", "R", 1],
      ],
    ],
  },
  {
    slug: "biotechnology", name: "BS Biotechnology", aliases: ["biotech","biotechnology"], id: 116,
    semesters: [
      [
        ["BIO5101", "Introduction to Biotechnology", "R", 3],
        ["CS101", "Introduction to Computing", "R", 3],
        ["ECO401", "Economics", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["BIO504T", "Biochemistry I (Theory)", "R", 3],
        ["BIO5105", "Cell Biology", "R", 3],
        ["CHE201", "Physical Chemistry", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["BIO505T", "Essentials of Genetics (Theory)", "R", 3],
        ["MB502T", "Molecular Biology (Theory)", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["BT611T", "Food Biotechnology (Theory)", "R", 2],
        ["BT614T", "Industrial Biotechnology (Theory)", "R", 2],
        ["MIC501T", "Microbiology (Theory)", "R", 2],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["BIO732", "Gene Manipulation and Genetic Engineering", "R", 3],
        ["BT501", "Health Biotechnology", "R", 3],
        ["SOC604", "Community Development", "R", 3],
        ["BT605", "Biosafety & Bioethics", "R", 2],
        ["BIO504P", "Biochemistry I (Practical)", "R", 1],
        ["BIO505P", "Essentials of Genetics (Practical)", "R", 1],
        ["BT511P", "Introduction to Biotechnology (Practical)", "R", 1],
        ["MB501P", "Cell Biology (Practical)", "R", 1],
        ["MB502P", "Molecular Biology (Practical)", "R", 1],
        ["MIC501P", "Microbiology (Practical)", "R", 1],
      ],
      [
        ["BIO506T", "Biochemistry II (Theory)", "R", 3],
        ["BT101", "Ecology, Biodiversity & Evolution-I", "R", 3],
        ["BT601", "Virology", "R", 3],
        ["CS201", "Introduction to Programming", "R", 3],
        ["BT513T", "Principles of Biochemical Engineering (Theory)", "R", 2],
        ["BT612T", "Fermentation Technology (Theory)", "R", 2],
      ],
      [
        ["BIF101", "Introduction to Bioinformatics", "R", 3],
        ["BIO401", "Biostatistics", "R", 3],
        ["BIO503", "Biological Physics", "R", 3],
        ["BT302", "Immunology", "R", 3],
        ["BT405", "Nano Biotechnology", "R", 3],
        ["BT504", "Genomics and Proteomics", "R", 3],
        ["CS442", "Introduction to Data Science", "R", 3],
      ],
      [
        ["BIO6221", "Internship", "R", 3],
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["MCD504", "Acting and Performance", "R", 3],
        ["BIF401P", "Bioinformatics I (Practical)", "R", 1],
        ["BIO506P", "Biochemistry II (Practical)", "R", 1],
        ["BT513P", "Principles of Biochemical Engineering (Practical)", "R", 1],
        ["BT611P", "Food Biotechnology (Practical)", "R", 1],
        ["BT612P", "Fermentation Technology (Practical)", "R", 1],
        ["BT614P", "Industrial Biotechnology (Practical)", "R", 1],
      ],
      [
        ["BIO6222", "Capstone Project", "R", 3],
        ["BT401", "Genetic Resources & Conservation", "R", 3],
        ["BT503", "Environment Biotechnology", "R", 3],
        ["BT505", "Biosensors", "R", 3],
        ["BT613T", "Agriculture Biotechnology (Theory)", "R", 2],
      ],
    ],
  },
  {
    slug: "business-administration", name: "BS Business Administration (BBA)", aliases: ["bba","business administration"], id: 2,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["MGT503", "Principles of Management", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT101", "Financial Accounting", "R", 3],
        ["MGT301", "Principles of Marketing", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["MGT501", "Human Resource Management", "R", 3],
        ["MGT611", "Business & Labor Law", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["ECO302", "Principles of Microeconomics", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["ECO402", "Microeconomics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT402", "Cost & Management Accounting", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["GSC101", "General Science", "E", 3],
        ["MGT520", "International Business", "E", 3],
        ["MKT501", "Marketing Management", "E", 3],
        ["PHY101", "Physics", "E", 3],
      ],
      [
        ["ACC501", "Business Finance", "R", 3],
        ["MGT502", "Organizational Behaviour", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["ECO403", "Macroeconomics", "E", 3],
        ["ECO404", "Managerial Economics", "E", 3],
        ["MGMT627", "Project Management", "E", 3],
        ["MGT613", "Production / Operations Management", "E", 3],
      ],
      [
        ["MGMT622", "Management Skills", "R", 3],
        ["MGT201", "Financial Management", "R", 3],
        ["MGT510", "Total Quality Management", "R", 3],
        ["MGTI699", "Internship / Field Experience", "R", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MCM601", "Media Management", "E", 3],
      ],
      [
        ["MGT415", "Introduction to Business Analytics", "R", 3],
        ["MGT603", "Strategic Management", "R", 3],
        ["MGT699", "Capstone Project", "R", 3],
        ["BNK601", "Banking Laws & Practices", "E", 3, "Banking"],
        ["BNK603", "Consumer Banking", "E", 3, "Banking"],
        ["EDU406", "Critical Thinking and reflective Practice", "E", 3],
        ["FIN621", "Financial Statement Analysis", "E", 3, "Finance"],
        ["FIN622", "Corporate Finance", "E", 3, "Finance"],
        ["HRM627", "Human Resource Development", "E", 3, "Human Resource Management"],
        ["HRM630", "International Human Resource Management", "E", 3, "Human Resource Management"],
        ["MGMT614", "Supply Chain Management", "E", 3, "Supply Chain Management"],
        ["MGMT615", "Transportation & Logistics Management", "E", 3, "Supply Chain Management"],
        ["MKT530", "Consumer Behaviour", "E", 3, "Marketing"],
        ["MKT624", "Brand Management", "E", 3, "Marketing"],
        ["PSY405", "Personality Psychology", "E", 3],
      ],
      [
        ["EDU401", "Contemporary Issues and Trends in Education", "E", 3],
        ["FIN623", "Taxation Management", "E", 3],
        ["FIN625", "Credit & Risk Management", "E", 3, "Banking|Finance"],
        ["FIN630", "Investment Analysis & Portfolio Management", "E", 3, "Finance"],
        ["HRM617", "Training and Development", "E", 3, "Human Resource Management"],
        ["HRM626", "Recruitment and selection", "E", 3, "Human Resource Management"],
        ["MGMT617", "Production Planning and Inventory Control", "E", 3, "Supply Chain Management"],
        ["MGMT631", "Enterprise Resource Planning", "E", 3, "Supply Chain Management"],
        ["MGT401", "Financial Accounting II", "E", 3],
        ["MGT601", "SME Management", "E", 3],
        ["MGT604", "Management of Financial Institutions", "E", 3, "Banking"],
        ["MGT610", "Business Ethics", "E", 3],
        ["MKT621", "Advertising & Promotion", "E", 3, "Marketing"],
        ["MKT625", "Services Marketing", "E", 3, "Marketing"],
        ["SOC617", "Social Entrepreneurship", "E", 3],
      ],
    ],
  },
  {
    slug: "commerce", name: "BS Commerce", aliases: ["bcom","commerce"], id: 3,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["MGT503", "Principles of Management", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT101", "Financial Accounting", "R", 3],
        ["MGT301", "Principles of Marketing", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["PAK302", "Pakistan Studies", "R", 2],
      ],
      [
        ["ACC311", "Fundamentals of Auditing", "R", 3],
        ["MGT611", "Business & Labor Law", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["ECO302", "Principles of Microeconomics", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["ECO402", "Microeconomics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT402", "Cost & Management Accounting", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["FIN623", "Taxation Management", "E", 3],
        ["GSC101", "General Science", "E", 3],
        ["MGT520", "International Business", "E", 3],
        ["PHY101", "Physics", "E", 3],
      ],
      [
        ["ACC501", "Business Finance", "R", 3],
        ["MGT501", "Human Resource Management", "R", 3],
        ["MKT501", "Marketing Management", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["ECO403", "Macroeconomics", "E", 3],
        ["ECO404", "Managerial Economics", "E", 3],
      ],
      [
        ["MGT201", "Financial Management", "R", 3],
        ["MGT612", "Corporate Law", "R", 3],
        ["MGT613", "Production / Operations Management", "R", 3],
        ["MGTI699", "Internship / Field Experience", "R", 3],
        ["PSY405", "Personality Psychology", "E", 3],
        ["SOC617", "Social Entrepreneurship", "E", 3],
      ],
      [
        ["BNK603", "Consumer Banking", "R", 3],
        ["FIN624", "Islamic Modes of Finance", "R", 3],
        ["MGMT614", "Supply Chain Management", "R", 3],
        ["MGT699", "Capstone Project", "R", 3],
        ["ECO501", "Development Economics", "E", 3],
        ["EDU406", "Critical Thinking and reflective Practice", "E", 3],
        ["MGT404", "Managerial Accounting", "E", 3],
        ["MGT605", "Advanced Cost and Management Accounting", "E", 3],
      ],
      [
        ["BNK612", "Financial Jurisprudence in Islam", "R", 3],
        ["MGMT615", "Transportation & Logistics Management", "R", 3],
        ["MGT302", "Digital Marketing", "R", 3],
        ["STA302", "Data Analytics and Business Intelligence", "R", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MCM601", "Media Management", "E", 3],
      ],
    ],
  },
  {
    slug: "computer-science", name: "BS Computer Science", aliases: ["bscs","cs","computer science"], id: 4,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["CS201", "Introduction to Programming", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["ECO401", "Economics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["MTH100", "General Mathematics", "D", 3],
        ["CS201P", "Introduction to Programming (Practical)", "R", 1],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["MTH501", "Linear Algebra", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["CS302", "Digital Logic Design", "E", 3],
        ["CS304", "Object Oriented Programming", "E", 3],
        ["MTH104", "Sets and Logic", "D", 3],
        ["CS525", "Professional Practices", "R", 2],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["CS302P", "Digital Logic Design (Practical)", "E", 1],
        ["CS304P", "Object Oriented Programming (Practical)", "E", 1],
      ],
      [
        ["CS504", "Software Engineering - I", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["CS301", "Data Structures", "E", 3],
        ["CS403", "Database Management Systems", "E", 3],
        ["PHY101", "Physics", "E", 3],
        ["PHY301", "Circuit Theory", "E", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["CS301P", "Data Structures (Practical)", "E", 1],
        ["CS403P", "Database Management Systems (Practical)", "E", 1],
      ],
      [
        ["CS601", "Data Communication", "R", 3],
        ["MCM301", "Communication skills", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["CS401", "Computer Architecture and Assembly Language Programming", "E", 3],
        ["CS604", "Operating Systems", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["CS401P", "Computer Architecture and Assembly Language Programming (Practical)", "E", 1],
        ["CS604P", "Operating Systems (Practical)", "E", 1],
      ],
      [
        ["CS205", "Information Security", "R", 3],
        ["CS402", "Theory of Automata", "R", 3],
        ["CS502", "Fundamentals of Algorithms", "R", 3],
        ["CS607", "Artificial Intelligence", "R", 3],
        ["MTH401", "Differential Equations", "E", 3],
        ["MTH5102", "Calculus II", "E", 3],
        ["MTH603", "Numerical Analysis", "E", 3],
      ],
      [
        ["CS435", "Cloud Computing", "R", 3],
        ["CSI619", "Field Experience / Internship", "R", 3],
        ["CS202", "Fundamentals of Front End Development", "E", 3, "Computer Science|Software Engineering"],
        ["CS306", "Introduction to Python", "E", 3, "Artificial Intelligence|Computer Science|Data Science|Information Technology|Software Engineering"],
        ["CS314", "Introduction to Cellular Networks", "E", 3, "Computer Science"],
        ["CS407", "Routing and Switching", "E", 3, "Information Technology"],
        ["CS408", "Human Computer Interaction", "E", 3, "Computer Science|Software Engineering"],
        ["CS411", "Visual Programming", "E", 3, "Computer Science"],
        ["CS441", "Big Data Concepts", "E", 3, "Data Science"],
        ["CS442", "Introduction to Data Science", "E", 3, "Data Science"],
        ["CS505", "Virtual Systems and Services", "E", 3, "Information Technology"],
        ["CS510", "Software Requirements and Specifications", "E", 3, "Software Engineering"],
        ["CS511", "Web Engineering", "E", 3, "Information Technology|Software Engineering"],
        ["CS521", "Web Systems and Technologies", "E", 3, "Information Technology"],
        ["CS605", "Software EngineeringII", "E", 3, "Computer Science|Software Engineering"],
        ["CS620", "Modelling and Simulation", "E", 3, "Artificial Intelligence"],
        ["STA302", "Data Analytics and Business Intelligence", "E", 3, "Artificial Intelligence|Data Science"],
        ["STA630", "Research Methods", "E", 3, "Computer Science"],
        ["STAT404", "Regression and Correlation", "E", 3, "Artificial Intelligence"],
      ],
      [
        ["CS619", "Final Project - CS619", "R", 3],
        ["CS699", "Professional Certification", "R", 3],
        ["CS311", "Introduction to Web Services Development", "E", 3, "Computer Science"],
        ["CS405", "Database Programming using Oracle 11g", "E", 3, "Computer Science"],
        ["CS506", "Web Design and Development", "E", 3, "Computer Science"],
        ["CS513", "Advanced Data Analytics and Business Intelligence", "E", 3, "Artificial Intelligence"],
        ["CS514", "Internet of Things (IoT)", "E", 3, "Information Technology"],
        ["CS603", "Software Architecture and Design", "E", 3, "Computer Science"],
        ["CS608", "Software Verification and Validation", "E", 3, "Software Engineering"],
        ["CS609", "System Programming", "E", 3, "Computer Science"],
        ["CS611", "Software Quality Engineering", "E", 3, "Software Engineering"],
        ["CS614", "Data Warehousing", "E", 3, "Computer Science|Data Science"],
        ["CS615", "Software Project Management", "E", 3, "Software Engineering"],
        ["CS621", "Parallel and Distributed Computing", "E", 3, "Computer Science"],
        ["CS626", "Data Mining Techniques", "E", 3, "Artificial Intelligence|Data Science"],
        ["CS628", "Machine Learning", "E", 3, "Artificial Intelligence|Data Science"],
        ["CS642", "Next Generation Networks", "E", 3, "Information Technology"],
        ["IT602", "Information Technology Infrastructure", "E", 3, "Information Technology"],
        ["MTH601", "Operations Research", "E", 3, "Computer Science"],
        ["SE602", "Software Re-Engineering", "E", 3, "Software Engineering"],
        ["SE601", "Software Construction & Development", "E", 2, "Software Engineering"],
      ],
      [
        ["CS312", "Database Modeling and Design", "E", 3, "Software Engineering"],
        ["CS315", "Network Security", "E", 3, "Information Technology"],
        ["CS409", "Introduction to Database Administration", "E", 3, "Information Technology"],
        ["CS501", "Advance Computer Architecture", "E", 3, "Computer Science"],
        ["CS515", "Advanced Database Management System", "E", 3, "Computer Science|Information Technology"],
        ["CS602", "Computer Graphics", "E", 3, "Computer Science"],
        ["CS606", "Compiler Construction", "E", 3, "Computer Science"],
        ["CS627", "Cyber Security", "E", 3, "Information Technology"],
        ["CS631", "Deep Learning", "E", 3, "Artificial Intelligence|Data Science"],
        ["IT430", "E-Commerce", "E", 3, "Information Technology"],
        ["STA621", "Time Series Analysis", "E", 3, "Data Science"],
      ],
    ],
  },
  {
    slug: "data-science", name: "BS Data Science", aliases: ["bsds","data science","datascience"], id: 260,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["PHY101", "Physics", "E", 3],
        ["PHY301", "Circuit Theory", "E", 3],
        ["MTH100", "General Mathematics", "D", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["CS201", "Introduction to Programming", "R", 3],
        ["CS302", "Digital Logic Design", "R", 3],
        ["CS442", "Introduction to Data Science", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["ECO401", "Economics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["MTH104", "Sets and Logic", "D", 3],
        ["CS201P", "Introduction to Programming (Practical)", "R", 1],
      ],
      [
        ["CS301", "Data Structures", "R", 3],
        ["CS304", "Object Oriented Programming", "R", 3],
        ["CS607", "Artificial Intelligence", "R", 3],
        ["MTH401", "Differential Equations", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["CS301P", "Data Structures (Practical)", "R", 1],
        ["CS304P", "Object Oriented Programming (Practical)", "R", 1],
      ],
      [
        ["CS401", "Computer Architecture and Assembly Language Programming", "R", 3],
        ["CS403", "Database Management Systems", "R", 3],
        ["MCM301", "Communication skills", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["MTH501", "Linear Algebra", "R", 3],
        ["CS525", "Professional Practices", "R", 2],
        ["CS403P", "Database Management Systems (Practical)", "R", 1],
      ],
      [
        ["CS502", "Fundamentals of Algorithms", "R", 3],
        ["CS604", "Operating Systems", "R", 3],
        ["CS626", "Data Mining Techniques", "R", 3],
        ["CSI619", "Field Experience / Internship", "R", 3],
        ["MTH603", "Numerical Analysis", "R", 3],
        ["CS306", "Introduction to Python", "E", 3],
        ["CS402", "Theory of Automata", "E", 3],
      ],
      [
        ["CS504", "Software Engineering - I", "R", 3],
        ["CS601", "Data Communication", "R", 3],
        ["CS614", "Data Warehousing", "R", 3],
        ["CS628", "Machine Learning", "E", 3],
        ["CS631", "Deep Learning", "E", 3],
      ],
      [
        ["CS619", "Final Project - CS619", "R", 3],
        ["CS621", "Parallel and Distributed Computing", "R", 3],
        ["CS630", "Data Visualization and Digital Storytelling", "R", 3],
        ["CS699", "Professional Certification", "R", 3],
        ["CS514", "Internet of Things (IoT)", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT610", "Business Ethics", "E", 3],
      ],
      [
        ["CS205", "Information Security", "R", 3],
        ["STAT404", "Regression and Correlation", "R", 3],
        ["CS513", "Advanced Data Analytics and Business Intelligence", "E", 3],
        ["CS515", "Advanced Database Management System", "E", 3],
      ],
    ],
  },
  {
    slug: "economics", name: "BS Economics", aliases: ["economics"], id: 154,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ECO302", "Principles of Microeconomics", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ECO303", "Principles of Macroeconomics", "R", 3],
        ["ECO402", "Microeconomics", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["ECO403", "Macroeconomics", "R", 3],
        ["ECO501", "Development Economics", "R", 3],
        ["ECO606", "Mathematical Economics I", "R", 3],
        ["EDU403", "Art, Crafts and Calligraphy", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ECO601", "Business Econometrics", "R", 3],
        ["ECO603", "International Economics", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["GSC101", "General Science", "E", 3],
        ["PHY101", "Physics", "E", 3],
      ],
      [
        ["ECO607", "Mathematical Economics II", "R", 3],
        ["ECO610", "Issues in the Economy of Pakistan", "R", 3],
        ["ECO614", "Microeconomic Analysis", "R", 3],
        ["ENG301", "Business Communication", "R", 3],
        ["HRM627", "Human Resource Development", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
      ],
      [
        ["ECO609", "Advanced Econometrics", "R", 3],
        ["ECO613", "Globalization and Economics", "R", 3],
        ["ECO616", "Macroeconomic Analysis", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["STAT404", "Regression and Correlation", "R", 3],
      ],
      [
        ["ECO404", "Managerial Economics", "R", 3],
        ["ECO605", "Financial Economics", "R", 3],
        ["ECO608", "Agricultural Economics", "R", 3],
        ["ECO615", "Poverty and Income Distribution", "R", 3],
        ["ECOI619", "Internship Report - Economics", "R", 3],
      ],
      [
        ["BNK611", "Economic Ideology in Islam", "R", 3],
        ["ECO499A", "Final Year Project-Economics", "R", 3],
        ["ECO604", "Monetary Economics", "R", 3],
        ["ECO612", "Population Economics", "R", 3],
        ["ECO622", "Energy Economics", "R", 3],
      ],
    ],
  },
  {
    slug: "english", name: "BS English (Applied Linguistics)", aliases: ["english"], id: 167,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["ENG502", "Introduction to Linguistics", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["ENG501", "History of English Language", "R", 3],
        ["ENG522", "Applied Linguistics", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["EDU403", "Art, Crafts and Calligraphy", "R", 3],
        ["ENG507", "Phonetics and Phonology", "R", 3],
        ["ENG508", "Semantics and Pragmatics", "R", 3],
        ["ENG509", "Morphology and Syntax", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ENG503", "Introduction to English Language Teaching", "R", 3],
        ["ENG504", "Second Language Acquisition", "R", 3],
        ["ENG506", "World Englishes", "R", 3],
        ["ENG510", "Sociolinguistics", "R", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["GSC101", "General Science", "E", 3],
      ],
      [
        ["EDU406", "Critical Thinking and reflective Practice", "R", 3],
        ["ENG505", "Language Learning Theories", "R", 3],
        ["ENG511", "Psycholinguistics", "R", 3],
        ["ENG512", "Bilingualism", "R", 3],
        ["ENG518", "Research Methodology in ELT", "R", 3],
      ],
      [
        ["ENG513", "Language Teaching Methods", "R", 3],
        ["ENG514", "Teaching of Listening and Speaking Skills", "R", 3],
        ["ENG515", "Teaching of Reading and Writing Skills", "R", 3],
        ["ENG529", "Technology in Language Teaching", "R", 3],
        ["MGT501", "Human Resource Management", "R", 3],
      ],
      [
        ["ENG498", "Field Work", "R", 3],
        ["ENG516", "Teaching Business Communication", "R", 3],
        ["ENG517", "Computer Assisted Language Learning", "R", 3],
        ["ENG523", "Discourse Analysis", "R", 3],
        ["PSY403", "Social Psychology", "R", 3],
      ],
      [
        ["ENG499", "Capstone Project", "R", 3],
        ["ENG519", "Curriculum Design", "R", 3],
        ["ENG524", "Critical Discourse Analysis", "R", 3],
        ["ENG527", "Language and Gender", "R", 3],
        ["MCM304", "Mass Media in Pakistan", "R", 3],
      ],
    ],
  },
  {
    slug: "information-technology", name: "BS Information Technology", aliases: ["bsit","it","information technology"], id: 7,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["PHY101", "Physics", "E", 3],
        ["PHY301", "Circuit Theory", "E", 3],
        ["MTH100", "General Mathematics", "D", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MCM301", "Communication skills", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["CS201", "Introduction to Programming", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["MTH104", "Sets and Logic", "D", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["CS201P", "Introduction to Programming (Practical)", "E", 1],
      ],
      [
        ["CS302", "Digital Logic Design", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["MTH501", "Linear Algebra", "R", 3],
        ["CS304", "Object Oriented Programming", "E", 3],
        ["CS403", "Database Management Systems", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["CS304P", "Object Oriented Programming (Practical)", "E", 1],
        ["CS403P", "Database Management Systems (Practical)", "E", 1],
      ],
      [
        ["CS401", "Computer Architecture and Assembly Language Programming", "R", 3],
        ["CS504", "Software Engineering - I", "R", 3],
        ["CS601", "Data Communication", "R", 3],
        ["MTH401", "Differential Equations", "R", 3],
        ["CS301", "Data Structures", "E", 3],
        ["CS525", "Professional Practices", "R", 2],
        ["CS301P", "Data Structures (Practical)", "E", 1],
      ],
      [
        ["CS306", "Introduction to Python", "R", 3],
        ["CS402", "Theory of Automata", "R", 3],
        ["CS409", "Introduction to Database Administration", "R", 3],
        ["CS502", "Fundamentals of Algorithms", "R", 3],
        ["CS604", "Operating Systems", "R", 3],
        ["CS610", "Computer Networks", "R", 3],
      ],
      [
        ["CS205", "Information Security", "R", 3],
        ["CS435", "Cloud Computing", "R", 3],
        ["CS511", "Web Engineering", "R", 3],
        ["CS521", "Web Systems and Technologies", "R", 3],
        ["CS607", "Artificial Intelligence", "R", 3],
        ["CSI619", "Field Experience / Internship", "R", 3],
        ["IT601", "System and Network Administration", "R", 3],
      ],
      [
        ["CS619", "Final Project - CS619", "R", 3],
        ["CS627", "Cyber Security", "R", 3],
        ["CS699", "Professional Certification", "R", 3],
        ["IT602", "Information Technology Infrastructure", "R", 3],
        ["CS314", "Introduction to Cellular Networks", "E", 3],
        ["CS315", "Network Security", "E", 3],
        ["CS407", "Routing and Switching", "E", 3],
        ["CS505", "Virtual Systems and Services", "E", 3],
        ["CS642", "Next Generation Networks", "E", 3],
      ],
      [
        ["CS621", "Parallel and Distributed Computing", "R", 3],
        ["MTH603", "Numerical Analysis", "R", 3],
        ["MGT211", "Introduction To Business", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT610", "Business Ethics", "E", 3],
      ],
    ],
  },
  {
    slug: "islamic-studies", name: "BS Islamic Studies", aliases: ["islamic studies"], id: 261,
    semesters: [
      [
        ["CS001", "VU-Computer Proficiency License", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["ISL1151", "Arabic Through Quranic Text", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3, "Business Studies"],
        ["URD101", "Urdu", "R", 3],
        ["ISL202", "Islamic Studies", "R", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["ISL1252", "Introduction of Topics of Holy Qur’an", "R", 3],
        ["ISL1253", "Arabic Language – I", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["EDU101", "Foundations of Education", "E", 3],
        ["PSC201", "International Relations", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["FHQ1101", "Fehm e Quran", "R", 1],
      ],
      [
        ["ISL2351", "Textual Study of al-Qur’an-I", "R", 3],
        ["ISL2352", "History & Compilation of Hadith", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["EDU433", "Professionalism in Teaching", "E", 3],
        ["IT430", "E-Commerce", "E", 3],
        ["MGT301", "Principles of Marketing", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["FHQ1102", "Fehm e Quran II", "R", 1],
      ],
      [
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["GSC101", "General Science", "R", 3],
        ["ISL2453", "Textual Study of al-Qur’an – II", "R", 3],
        ["ISL2454", "History of Fiqh", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "R", 3],
        ["BNK612", "Financial Jurisprudence in Islam", "E", 3],
        ["EDU512", "Teaching of Islamic Studies", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
      ],
      [
        ["ISL3560", "Study of Sirah of Holy Prophet (PBUH)", "R", 3],
        ["ISL3561", "Textual Study of al-Qur’an – III", "R", 3],
        ["ISL3562", "Textual Study of Hadith", "R", 3],
        ["ISL3563", "Arabic Language II", "R", 3],
        ["ISL3564", "Internship/ Field Study", "R", 3],
      ],
      [
        ["ISL3665", "Textual Study of al-Qur’an – IV", "R", 3],
        ["ISL3666", "Ulum-ul-Quran", "R", 3],
        ["ISL3667", "Textual Study of Islamic Fiqh", "R", 3],
        ["ISL3668", "Al- Dawah wal Irshad", "R", 3],
        ["ISL3669", "Methods of Research", "R", 3],
      ],
      [
        ["ISL4760", "History of Tafsir and its Principles", "R", 3],
        ["ISL4761", "Ulum al Hadith", "R", 3],
        ["ISL4762", "Usul-ul-Fiqh", "R", 3],
        ["ISL4763", "Islam and Science", "R", 3],
        ["ISL4764", "Study of World Religions", "R", 3],
      ],
      [
        ["ISL4865", "Islamic Culture and Civilization", "R", 3],
        ["ISL4869", "Capstone Project/Thesis", "R", 3],
        ["ISL4801", "Study of Tasawwuf", "E", 3],
        ["ISL4802", "Islamic Political Thought", "E", 3],
        ["ISL4803", "Islamic and International Humanitarian Law", "E", 3],
        ["ISL4804", "Introduction to Orientalism", "E", 3],
        ["ISL4866", "Introduction to Objectives of Shari’ah", "E", 3],
        ["ISL4867", "The Ethics of Disagreement in Islam", "E", 3],
        ["ISL4868", "Principles of Economics in Islam", "E", 3],
      ],
    ],
  },
  {
    slug: "mass-communication", name: "BS Mass Communication", aliases: ["mass communication","mcm"], id: 8,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MCM301", "Communication skills", "R", 3],
        ["MCM304", "Mass Media in Pakistan", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["MCM310", "Journalistic Writing", "R", 3],
        ["MCM311", "Reporting and Sub-Editing", "R", 3],
        ["MCM401", "Fundamentals of Public Relations", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["URD101", "Urdu", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["GSC101", "General Science", "R", 3],
        ["MCM411", "Introduction to Broadcasting", "R", 3],
        ["MCM501", "Advertising for Print and Electronic Media", "R", 3],
        ["MCM511", "Theories of Communication", "R", 3],
        ["MCM610", "Mass Communication Law & Ethics", "R", 3],
      ],
      [
        ["MCM514", "Feature & Column Writing", "R", 3],
        ["MCM601", "Media Management", "R", 3],
        ["PSC401", "Public International Law", "R", 3],
        ["EDU403", "Art, Crafts and Calligraphy", "E", 3],
        ["MGT211", "Introduction To Business", "E", 3],
        ["MGT301", "Principles of Marketing", "E", 3],
        ["SOC401", "Cultural Anthropology", "E", 3],
      ],
      [
        ["MCM515", "Radio News Reporting & Production", "R", 3],
        ["MCM532", "Magazine Journalism", "R", 3],
        ["MCMI619", "Internship Report-Mass Communication", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["CS204", "Cyber Law", "E", 3],
        ["IT430", "E-Commerce", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT503", "Principles of Management", "E", 3],
      ],
      [
        ["MCM431", "Development Communication", "R", 3],
        ["MCM516", "TV News Reporting & Production", "R", 3],
        ["MCM517", "Online Journalism", "R", 3],
        ["MCM520", "Contemporary Mass Media", "R", 3],
        ["PSC201", "International Relations", "R", 3],
        ["MCM612", "Media Lab", "R", 2],
      ],
      [
        ["MCM499", "Capstone Project", "R", 3],
        ["MCM531", "Community Journalism", "R", 3],
        ["MCM604", "International Communication", "R", 3],
        ["MCM611", "Seminar on Contemporary Issues in Media", "R", 3],
        ["SOC610", "Electronic Media & Virtual Community", "R", 3],
      ],
    ],
  },
  {
    slug: "mathematics", name: "BS Mathematics", aliases: ["mathematics","maths"], id: 161,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["MTH104", "Sets and Logic", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["MTH100", "General Mathematics", "D", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["CS306", "Introduction to Python", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["GSC101", "General Science", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["MTH5102", "Calculus II", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["CS306P", "Introduction to Python (Practical)", "R", 1],
      ],
      [
        ["MGT602", "Entrepreneurship", "R", 3],
        ["MTH5204", "Modelling and Simulation", "R", 3],
        ["MTH5205", "Calculus III", "R", 3],
        ["MTH5206", "Linear Algebra", "R", 3],
        ["MTH5207", "Mechanics I", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ENG301", "Business Communication", "R", 3],
        ["MTH5208", "Ordinary Differential Equations", "R", 3],
        ["MTH5209", "Discrete Mathematics", "R", 3],
        ["MTH5210", "Group Theory", "R", 3],
        ["MTH5211", "Mechanics II", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
      ],
      [
        ["MCD504", "Acting and Performance", "R", 3],
        ["MTH603", "Numerical Analysis", "R", 3],
        ["MTH621", "Real Analysis I", "R", 3],
        ["MTH643", "Introduction to MATLAB", "R", 3],
        ["MTH646", "Partial Differential Equations", "R", 3],
      ],
      [
        ["EDU510", "Teaching of Mathematics", "R", 3],
        ["MTH601", "Operations Research", "R", 3],
        ["MTH631", "Real Analysis II", "R", 3],
        ["MTH634", "Topology", "R", 3],
        ["MTH641", "Functional Analysis", "R", 3],
      ],
      [
        ["BIF401", "Bioinformatics I", "R", 3],
        ["MTH622", "Vectors and Classical Mechanics", "R", 3],
        ["MTH632", "Complex Analysis and Differential Geometry", "R", 3],
        ["MTH6401", "Internship / Field Experience", "R", 3],
        ["PHY101", "Physics", "R", 3],
      ],
      [
        ["MTH6402", "Capstone Project", "R", 3],
        ["MTH642", "Fluid Mechanics", "R", 3],
        ["MTH644", "Measure Theory", "R", 3],
        ["MTH645", "Fuzzy Logic and Applications", "R", 3],
        ["MTH647", "Methods in Mathematical Physics", "R", 3],
      ],
    ],
  },
  {
    slug: "psychology", name: "BS Psychology", aliases: ["psychology","bs psychology"], id: 10,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["PSY101", "Introduction to Psychology", "R", 3],
        ["PSY502", "History & Systems of Psychology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["PSY404", "Abnormal Psychology", "R", 3],
        ["PSY405", "Personality Psychology", "R", 3],
        ["PSY512", "Gender Issues in Psychology", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["EDU403", "Art, Crafts and Calligraphy", "R", 3],
        ["PSY403", "Social Psychology", "R", 3],
        ["PSY504", "Cognitive Psychology", "R", 3],
        ["STA641", "Statistical Packages and its Applications", "R", 3],
        ["PSC201", "International Relations", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["BIO101", "Basic I-Biology", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PSY505", "Developmental Psychology", "R", 3],
        ["PSY515", "Cross Cultural Psychology", "R", 3],
        ["PSY611", "Ethical Issues in Psychology", "R", 3],
      ],
      [
        ["PSYP631", "Psychological Testing and Measurements", "R", 4],
        ["PSY401", "Clinical Psychology", "R", 3],
        ["PSY516", "Statistics in Psychology", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["MCM304", "Mass Media in Pakistan", "E", 3],
      ],
      [
        ["PSYP610", "Neurological Bases of Behavior", "R", 4],
        ["PSY406", "Educational Psychology", "R", 3],
        ["PSY632", "Theory & Practice of Counseling", "R", 3],
        ["SOC609", "Qualitative Research Methods", "R", 3],
        ["SOC301", "Introduction to Social Work", "E", 3],
        ["SOC401", "Cultural Anthropology", "E", 3],
      ],
      [
        ["PSY407", "Sport Psychology", "R", 3],
        ["PSY408", "Health Psychology", "R", 3],
        ["PSY409", "Positive Psychology", "R", 3],
        ["PSYI619", "Internship Report-Psychology", "R", 3],
        ["PSYP402", "Experimental Psychology", "R", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["SOC404", "Pakistani Society and Culture", "E", 3],
      ],
      [
        ["PSY499", "Capstone Project", "R", 3],
        ["PSY511", "Environmental Psychology", "R", 3],
        ["PSY513", "Forensic Psychology", "R", 3],
        ["ECO401", "Economics", "E", 3],
        ["MGT211", "Introduction To Business", "E", 3],
        ["PSY510", "Organizational Psychology", "E", 3],
        ["PSY514", "Consumer Psychology", "E", 3],
      ],
    ],
  },
  {
    slug: "public-administration", name: "BS Public Administration", aliases: ["bpa","public administration"], id: 11,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MGT503", "Principles of Management", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT101", "Financial Accounting", "R", 3],
        ["MGT111", "Introduction to Public Administration", "R", 3],
        ["MGT522", "Introduction to Public Policy", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["MGT301", "Principles of Marketing", "R", 3],
        ["MGT411", "Money & Banking", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["ECO302", "Principles of Microeconomics", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["ECO402", "Microeconomics", "E", 3],
        ["MGT501", "Human Resource Management", "E", 3],
        ["MGT611", "Business & Labor Law", "E", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["ACC501", "Business Finance", "E", 3],
        ["BIO101", "Basic I-Biology", "E", 3],
        ["GSC101", "General Science", "E", 3],
        ["MCM401", "Fundamentals of Public Relations", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT513", "Public Administration in Pakistan", "E", 3],
        ["PHY101", "Physics", "E", 3],
      ],
      [
        ["PAD603", "Governance, Democracy and Society", "R", 3],
        ["SOC401", "Cultural Anthropology", "R", 3],
        ["SOC404", "Pakistani Society and Culture", "R", 3],
        ["STA630", "Research Methods", "R", 3],
        ["ECO403", "Macroeconomics", "E", 3],
        ["ECO622", "Energy Economics", "E", 3],
      ],
      [
        ["MGT621", "Administrative Law and Accountability", "R", 3],
        ["PADI699", "Internship / Field Experience", "R", 3],
        ["ECO404", "Managerial Economics", "E", 3],
        ["ECO610", "Issues in the Economy of Pakistan", "E", 3],
        ["PSY405", "Personality Psychology", "E", 3],
        ["SOC607", "Urban Sociology", "E", 3],
        ["SOC612", "Political Sociology", "E", 3],
      ],
      [
        ["PAD699", "Capstone Project", "R", 3],
        ["SOC613", "Social Change and Transformation", "R", 3],
        ["SOC615", "Environmental Sociology", "R", 3],
        ["SOC617", "Social Entrepreneurship", "R", 3],
        ["EDU406", "Critical Thinking and reflective Practice", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
      ],
      [
        ["MGT603", "Strategic Management", "R", 3],
        ["SOC601", "Social Policy and Governance", "R", 3],
        ["SOC605", "Population Dynamics", "R", 3],
        ["SOC616", "Sociology of Globalization", "R", 3],
        ["MCM517", "Online Journalism", "E", 3],
        ["MCM601", "Media Management", "E", 3],
      ],
    ],
  },
  {
    slug: "sociology", name: "BS Sociology", aliases: ["sociology"], id: 152,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["SOC101", "Introduction to Sociology", "R", 3],
        ["SOC201", "Social Statistics", "R", 3],
        ["SOC301", "Introduction to Social Work", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["ETH100", "Effective Citizenship", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "R", 3],
        ["SOC302", "Sociological Theories", "R", 3],
        ["SOC404", "Pakistani Society and Culture", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["MGT602", "Entrepreneurship", "R", 3],
        ["SOC401", "Cultural Anthropology", "R", 3],
        ["SOC403", "Gender Studies", "R", 3],
        ["SOC602", "Sociology of Education", "R", 3],
        ["URD101", "Urdu", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["GSC101", "General Science", "R", 3],
        ["PSY403", "Social Psychology", "R", 3],
        ["SOC603", "Sociology of Development", "R", 3],
        ["SOC604", "Community Development", "R", 3],
        ["SOC605", "Population Dynamics", "R", 3],
      ],
      [
        ["MGT502", "Organizational Behaviour", "R", 3],
        ["SOC402", "Sociological Perspectives", "R", 3],
        ["SOC509", "Quantitative Research Methodology", "R", 3],
        ["SOC606", "Rural Sociology", "R", 3],
        ["MGT111", "Introduction to Public Administration", "E", 3],
        ["MGT522", "Introduction to Public Policy", "E", 3],
      ],
      [
        ["SOC607", "Urban Sociology", "R", 3],
        ["SOC608", "Sociology of Health", "R", 3],
        ["SOC609", "Qualitative Research Methods", "R", 3],
        ["SOC612", "Political Sociology", "R", 3],
        ["SOC613", "Social Change and Transformation", "R", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["MCM301", "Communication skills", "E", 3],
        ["MCM401", "Fundamentals of Public Relations", "E", 3],
      ],
      [
        ["PSY515", "Cross Cultural Psychology", "R", 3],
        ["SOC611", "Criminology", "R", 3],
        ["SOC614", "Sociology of Religion", "R", 3],
        ["SOC615", "Environmental Sociology", "R", 3],
        ["SOC616", "Sociology of Globalization", "R", 3],
        ["SOCI619", "Internship Report-Sociology", "R", 3],
      ],
      [
        ["EDU403", "Art, Crafts and Calligraphy", "R", 3],
        ["SOC499", "Capstone Project", "R", 3],
        ["SOC601", "Social Policy and Governance", "R", 3],
        ["SOC610", "Electronic Media & Virtual Community", "R", 3],
        ["SOC617", "Social Entrepreneurship", "R", 3],
      ],
    ],
  },
  {
    slug: "software-engineering", name: "BS Software Engineering", aliases: ["bsse","se","software engineering"], id: 91,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["CS201", "Introduction to Programming", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["MTH100", "General Mathematics", "D", 3],
        ["CS201P", "Introduction to Programming (Practical)", "R", 1],
        ["VU001", "Introduction to e-Learning", "R", 1],
      ],
      [
        ["CS302", "Digital Logic Design", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["CS304", "Object Oriented Programming", "E", 3],
        ["CS403", "Database Management Systems", "E", 3],
        ["ECO401", "Economics", "E", 3],
        ["MCM101", "Introduction to Mass Communication", "E", 3],
        ["PSY101", "Introduction to Psychology", "E", 3],
        ["SOC101", "Introduction to Sociology", "E", 3],
        ["MTH104", "Sets and Logic", "D", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
        ["CS304P", "Object Oriented Programming (Practical)", "E", 1],
        ["CS403P", "Database Management Systems (Practical)", "E", 1],
      ],
      [
        ["CS401", "Computer Architecture and Assembly Language Programming", "R", 3],
        ["CS504", "Software Engineering - I", "R", 3],
        ["MCM301", "Communication skills", "R", 3],
        ["CS301", "Data Structures", "E", 3],
        ["CS525", "Professional Practices", "R", 2],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["CS301P", "Data Structures (Practical)", "E", 1],
      ],
      [
        ["CS510", "Software Requirements and Specifications", "R", 3],
        ["CS603", "Software Architecture and Design", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["PHY101", "Physics", "E", 3],
        ["PHY301", "Circuit Theory", "E", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["CS601", "Data Communication", "R", 3],
        ["CS604", "Operating Systems", "R", 3],
        ["CS607", "Artificial Intelligence", "R", 3],
        ["CSI619", "Field Experience / Internship", "R", 3],
        ["CS306", "Introduction to Python", "E", 3],
        ["CS408", "Human Computer Interaction", "E", 3],
        ["CS608", "Software Verification and Validation", "E", 3],
        ["SE601", "Software Construction & Development", "E", 2],
        ["SE601P", "Software Construction & Development (Practical)", "E", 1],
      ],
      [
        ["CS611", "Software Quality Engineering", "R", 3],
        ["CS615", "Software Project Management", "R", 3],
        ["CS402", "Theory of Automata", "E", 3],
        ["CS442", "Introduction to Data Science", "E", 3],
        ["CS501", "Advance Computer Architecture", "E", 3],
        ["CS511", "Web Engineering", "E", 3],
        ["CS605", "Software EngineeringII", "E", 3],
        ["CS609", "System Programming", "E", 3],
        ["SE602", "Software Re-Engineering", "E", 3],
      ],
      [
        ["CS619", "Final Project - CS619", "R", 3],
        ["CS205", "Information Security", "R", 3],
        ["CS502", "Fundamentals of Algorithms", "R", 3],
        ["CS699", "Professional Certification", "R", 3],
        ["MTH401", "Differential Equations", "R", 3],
        ["MTH501", "Linear Algebra", "R", 3],
        ["CS515", "Advanced Database Management System", "E", 3],
        ["CS521", "Web Systems and Technologies", "E", 3],
        ["CS614", "Data Warehousing", "E", 3],
      ],
      [
        ["CS621", "Parallel and Distributed Computing", "R", 3],
        ["MTH603", "Numerical Analysis", "R", 3],
        ["MGT211", "Introduction To Business", "E", 3],
        ["MGT502", "Organizational Behaviour", "E", 3],
        ["MGT610", "Business Ethics", "E", 3],
      ],
    ],
  },
  {
    slug: "statistics", name: "BS Statistics", aliases: ["statistics"], id: 280,
    semesters: [
      [
        ["CS101", "Introduction to Computing", "R", 3],
        ["ECO401", "Economics", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["STA301", "Statistics and Probability", "R", 3],
        ["MTH302", "Business Mathematics & Statistics", "D", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["GSC101", "General Science", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["MTH5101", "Calculus I", "R", 3],
        ["STA642", "Probability Distributions", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["MCM301", "Communication skills", "R", 3],
        ["MTH5102", "Calculus II", "R", 3],
        ["PSY101", "Introduction to Psychology", "R", 3],
        ["STA5204", "Regression Analysis", "R", 3],
        ["STAT406", "Statistical Inference Methods", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
      ],
      [
        ["CS306", "Introduction to Python", "R", 3],
        ["CS403", "Database Management Systems", "R", 3],
        ["MGT211", "Introduction To Business", "R", 3],
        ["SOC605", "Population Dynamics", "R", 3],
        ["STA5209", "Data Analysis by Statistical Software-I", "R", 3],
        ["STA643", "Experimental Designs", "R", 3],
      ],
      [
        ["MCD504", "Acting and Performance", "R", 3],
        ["MGT510", "Total Quality Management", "R", 3],
        ["MTH601", "Operations Research", "R", 3],
        ["STA631", "Inferential Statistics", "R", 3],
        ["STA6310", "Probability and Probability Distributions-II", "R", 3],
        ["STA633", "Multivariate Analysis", "R", 3],
      ],
      [
        ["BIF401", "Bioinformatics I", "R", 3],
        ["ECO601", "Business Econometrics", "R", 3],
        ["EDU713", "Qualitative Research Methods in Education", "R", 3],
        ["STA632", "Sampling Techniques", "R", 3],
        ["STA644", "Non-Parametric Statistics", "R", 3],
      ],
      [
        ["CS620", "Modelling and Simulation", "R", 3],
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["STA621", "Time Series Analysis", "R", 3],
        ["STA6420", "Data Analysis by Statistical Softwares-II", "R", 3],
        ["STA6421", "Internship", "R", 3],
      ],
      [
        ["CS607", "Artificial Intelligence", "R", 3, "Data Analytics"],
        ["CS631", "Deep Learning", "R", 3, "Data Analytics"],
        ["CS723", "Probability and Stochastic Processes", "R", 3, "Data Analytics"],
        ["CS725", "Data Mining", "R", 3, "Data Analytics"],
        ["STA6422", "Capstone Project", "R", 3],
      ],
    ],
  },
  {
    slug: "zoology", name: "BS Zoology", aliases: ["zoology"], id: 168,
    semesters: [
      [
        ["BIO5105", "Cell Biology", "R", 3],
        ["CS101", "Introduction to Computing", "R", 3],
        ["ECO401", "Economics", "R", 3],
        ["ENG101", "English Comprehension", "R", 3],
        ["MTH100", "General Mathematics", "R", 3],
        ["ETH202", "Ethics (for Non-Muslims)", "E", 2],
        ["ISL202", "Islamic Studies", "E", 2],
      ],
      [
        ["CHE201", "Physical Chemistry", "R", 3],
        ["ENG201", "Business and Technical English Writing", "R", 3],
        ["MTH202", "Discrete Mathematics", "R", 3],
        ["ZOO512T", "Animal Diversity: Invertebrates (Theory)", "R", 3],
        ["ZOO513T", "Animal Diversity: Chordates (Theory)", "R", 3],
        ["PAK301", "Pakistan Studies", "R", 2],
      ],
      [
        ["BIO504T", "Biochemistry I (Theory)", "R", 3],
        ["BIO505T", "Essentials of Genetics (Theory)", "R", 3],
        ["MB502T", "Molecular Biology (Theory)", "R", 3],
        ["MGT602", "Entrepreneurship", "R", 3],
        ["ZOO516T", "Animal Form & Function-I (Theory)", "R", 3],
        ["PAK522", "Ideology and Constitution of Pakistan", "R", 2],
        ["ZOO501T", "Developmental Biology (Theory)", "R", 2],
      ],
      [
        ["SOC610", "Electronic Media & Virtual Community", "R", 3],
        ["ZOO510", "Economic Zoology", "R", 3],
        ["ZOO519T", "Physiology (Theory)", "R", 3],
        ["BT605", "Biosafety & Bioethics", "R", 2],
        ["BIO504P", "Biochemistry I (Practical)", "R", 1],
        ["BIO505P", "Essentials of Genetics (Practical)", "R", 1],
        ["MB501P", "Cell Biology (Practical)", "R", 1],
        ["MB502P", "Molecular Biology (Practical)", "R", 1],
        ["ZOO512P", "Animal Diversity: Invertebrates", "R", 1],
        ["ZOO513P", "Animal Diversity: Chordates (Practical)", "R", 1],
      ],
      [
        ["BIO401", "Biostatistics", "R", 3],
        ["BT101", "Ecology, Biodiversity & Evolution-I", "R", 3],
        ["CS201", "Introduction to Programming", "R", 3],
        ["ZOO503", "Zoogeography and Paleontology", "R", 3],
        ["ZOO504", "Wildlife", "R", 3],
        ["ZOO518T", "Applied Entomology and Pest Management (Theory)", "R", 3],
      ],
      [
        ["BIF101", "Introduction to Bioinformatics", "R", 3],
        ["BT302", "Immunology", "R", 3],
        ["BT601", "Virology", "R", 3],
        ["CS442", "Introduction to Data Science", "R", 3],
        ["MCD504", "Acting and Performance", "R", 3],
        ["ZOO507", "Principles of Animal Ecology", "R", 3],
        ["ZOO511T", "Principles of Systematics (Theory)", "R", 2],
      ],
      [
        ["EDU301", "General Methods of Teaching", "R", 3],
        ["ZOO6221", "Internship/Field Experience", "R", 3],
        ["ZOO501P", "Developmental Biology (Practical)", "R", 1],
        ["ZOO511P", "Principles of Systematics (Practical)", "R", 1],
        ["ZOO516P", "Animal Form & Function-I (Practical)", "R", 1],
        ["ZOO518P", "Applied Entomology and Pest Management (Practical)", "R", 1],
        ["ZOO519P", "Physiology (Practical)", "R", 1],
      ],
      [
        ["ZOO517T", "Animal Form & Function-II (Theory)", "R", 3],
        ["ZOO6222", "Capstone Project", "R", 3],
        ["BT512T", "Microbial Biotechnology (Theory)", "R", 2],
        ["MIC501T", "Microbiology (Theory)", "R", 2],
        ["ZOO603T", "Fish Biology (Theory)", "R", 2],
      ],
    ],
  },
];

export const VU_PROGRAMS: readonly VuProgram[] = RAW.map((p) => ({
  slug: p.slug,
  name: p.name,
  aliases: p.aliases,
  sourceUrl: `https://www.vu.edu.pk/AboutUs/ProgramDetails?StudyProgramID=${p.id}`,
  semesters: p.semesters.map((rows) => rows.map(([code, title, kind, credits, tracks]) => ({ code, title, kind, credits, tracks: tracks ? tracks.split("|") : [] }))),
}));

export function findVuProgram(slug: string | undefined | null): VuProgram | undefined {
  return slug ? VU_PROGRAMS.find((p) => p.slug === slug) : undefined;
}
